name: zlib-ng+crossbuild+package+release
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name: [zlib-ng]
        os_id: [debian, ubuntu]
        os_codename: [stretch, buster, bullseye, bionic, focal, jammy]
        arch: [amd64, armhf, arm64]
        zlib_compat: ["", "-D ZLIB_COMPAT=ON"]
        include:
          - arch: amd64
            CHOST: "x86_64-linux-gnu"
          - arch: armhf
            CHOST: "arm-linux-gnueabihf"
          - arch: arm64
            CHOST: "aarch64-linux-gnu"
          - zlib_compat: ""
            pretty_name: v2
            header_name: ZLIBNG_VERSION
          - zlib_compat: "-D ZLIB_COMPAT=ON"
            pretty_name: v1
            header_name: ZLIB_VERSION
        exclude:
          - os_id: debian
            os_codename: bionic
          - os_id: debian
            os_codename: focal
          - os_id: debian
            os_codename: jammy
          - os_id: ubuntu
            os_codename: stretch
          - os_id: ubuntu
            os_codename: buster
          - os_id: ubuntu
            os_codename: bullseye

    name: ${{ matrix.arch }} ${{ matrix.os_id }}:${{ matrix.os_codename }} ${{ matrix.name }} ${{ matrix.pretty_name }}
    env:
      opt_dir_name: "opt/local"
      github_branch: "develop"
      cxx_standard: "17"
      prerelease: true
      GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    outputs:
      draft_id_1: ${{ steps.draft_id_1.outputs.draft_id_1 }}
      draft_id_2: ${{ steps.draft_id_2.outputs.draft_id_2 }}

    steps:
      - name: Host - Checkout action
        uses: actions/checkout@v3

      - name: Host - phased updates # https://github.com/actions/runner-images/issues/7192
        run: echo 'APT::Get::Always-Include-Phased-Updates "false";' | sudo tee /etc/apt/apt.conf.d/99-phased-updates

      - name: Host - set up lunar repo -t lunar
        run: |
          printf '%b\n' 'Package: *\nPin: release n=lunar\nPin-Priority: 50' | sudo tee /etc/apt/preferences
          printf '%b\n' 'deb http://archive.ubuntu.com/ubuntu/ lunar main universe restricted' | sudo tee /etc/apt/sources.list.d/lunar.list

      - name: Host - update
        run: sudo apt-get update

      # - name: Host - upgrade
      #   run: sudo apt-get -y upgrade

      - name: Host - set up qemu-user-static binfmt-support from lunar
        run: sudo apt install -t lunar libpipeline1 qemu-user-static binfmt-support

      ### Why are we doing it like this and not using a container setup? That's how you're supposed to do it right?
      ### qemu-user-static and binfmt-support are not part of the runner imager https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
      ### We would need to modify the runner to install these before the container starts. Which you cannot do as there is no way to bootstrap the host.
      ### So we install them on the host then create/pull a custom docker image that we use to build teh multiarch targets.
      ### We are always on the host runner but can use any docker image we need with the access the qemu emulation required.
      ###
      ### We are using these pre configured toolchain images that allows me to remove 50% of the code/time from this action.
      ###
      ### https://github.com/userdocs/dcb/blob/main/Dockerfile

      - name: Host - Create docker multiarch ${{ matrix.arch }} container
        run: docker run --name multiarch -it -d -u 1001 -v ${{ github.workspace }}:/home/github ghcr.io/userdocs/dcb:${{ matrix.os_id }}-${{ matrix.os_codename }}-${{ matrix.arch }}

      ###############################################

      - name: Docker target - cmake and ninja download and install
        run: |
          docker exec multiarch curl -sNL "https://github.com/userdocs/cmake-crossbuild/releases/latest/download/${{ matrix.os_id }}-${{ matrix.os_codename }}-cmake-${{ matrix.arch }}.deb" -o ${{ matrix.os_id }}-${{ matrix.os_codename }}-cmake-${{ matrix.arch }}.deb
          docker exec multiarch sudo dpkg -i ${{ matrix.os_id }}-${{ matrix.os_codename }}-cmake-${{ matrix.arch }}.deb

      - name: Host - Git clone ${{ matrix.name }} develop
        run: git clone --single-branch --branch "${{ env.github_branch }}" --shallow-submodules --recurse-submodules --depth 1 https://github.com/zlib-ng/zlib-ng.git ${{ matrix.name }}

      - name: Host - Set zlib version to variable
        run: echo "zlib_ng_version=$(cat ${{ matrix.name }}/zlib.h.in | sed -rn 's|#define ${{ matrix.header_name }} "(.*)"|\1|p' | sed 's/\.[^.]*$//')" >> $GITHUB_ENV

      - name: Docker target - Cmake ${{ matrix.name }}
        run: |
          docker exec -w /root/${{ matrix.name }} multiarch cmake -Wno-dev -Wno-deprecated -G Ninja -B build \
          ${{ matrix.zlib_compat }} \
          -D CMAKE_VERBOSE_MAKEFILE="ON" \
          -D CMAKE_CXX_STANDARD="${{ env.cxx_standard }}" \
          -D CMAKE_CXX_STANDARD_REQUIRED=ON \
          -D CMAKE_CXX_EXTENSIONS=OFF \
          -D CMAKE_INSTALL_PREFIX="/root/build/${{ env.opt_dir_name }}"

      - name: Docker target - ${{ matrix.name }} - cmake build
        run: docker exec -w /root/${{ matrix.name }} multiarch cmake --build build

      - name: Docker target - ${{ matrix.name }} - cmake install
        run: docker exec -w /root/${{ matrix.name }} multiarch cmake --install build

      - name: Host - Set zlib release version
        if: matrix.pretty_name == 'v1'
        run: |
          echo "prerelease=false" >> $GITHUB_ENV

      - name: Docker target - Set deb dependencies for ${{ matrix.name }}
        run: echo "zlib-ng-deb-deps=none" >> $GITHUB_ENV

      - name: Docker target - ldconfig - create /etc/ld.so.conf.d/zlib-ng.conf
        run: |
          docker exec -w /root/build multiarch mkdir -p etc/ld.so.conf.d
          docker exec -w /root/build/etc/ld.so.conf.d multiarch bash -c "echo '/${{ env.opt_dir_name }}/lib' > zlib-ng.conf"

      - name: Host - Create deb packages
        uses: jiro4989/build-deb-action@v2
        with:
          package: "${{ matrix.name }}"
          package_root: build
          maintainer: userdocs
          compress_type: gzip
          version: "${{ env.zlib_ng_version }}"
          depends: "${{ env.zlib-ng-deb-deps }}"
          arch: "${{ matrix.arch }}"
          desc: "${{ matrix.name }}-${{ env.zlib_ng_version }}-${{ matrix.arch }} for ${{ matrix.os_id }}-${{ matrix.os_codename }}"

      - name: Host - Remove version from release name and use hyphens
        run: mv -f "${{ matrix.name }}_${{ env.zlib_ng_version }}_${{ matrix.arch }}.deb" "${{ matrix.os_id }}-${{ matrix.os_codename }}-${{ matrix.name }}-${{ matrix.arch }}.deb"

      - name: Host - "Create release - tag - assets"
        id: release_id
        uses: ncipollo/release-action@v1
        with:
          prerelease: ${{ env.prerelease }}
          draft: "true"
          artifacts: "${{ matrix.os_id }}-${{ matrix.os_codename }}-${{ matrix.name }}-${{ matrix.arch }}.deb"
          replacesArtifacts: true
          tag: "${{ env.zlib_ng_version }}"
          name: "${{ matrix.name }} ${{ env.zlib_ng_version }}"
          body: "${{ matrix.name }} built from github master on amd64 arm64 armhf for Debian Stretch Buster Bullseye and Ubuntu bionic Focal"
          allowUpdates: true

      - name: process v1
        id: draft_id_1
        if: matrix.pretty_name == 'v1'
        run: echo "draft_id_1=${{ steps.release_id.outputs.id }}" >> $GITHUB_OUTPUT

      - name: process v2
        id: draft_id_2
        if: matrix.pretty_name == 'v2'
        run: echo "draft_id_2=${{ steps.release_id.outputs.id }}" >> $GITHUB_OUTPUT

  publish_draft:
    name: Publish Drafts
    runs-on: ubuntu-22.04
    needs: [build]
    env:
      GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
      - name: Update draft to release
        run: |
          drafts=("${{ needs.build.outputs.draft_id_1 }}" "${{ needs.build.outputs.draft_id_2 }}")
          for d in "${drafts[@]}"; do
              gh api --silent /repos/${{ github.repository }}/releases/${d} -F 'draft=false'
          done